### ISSUE TITLE
Use CMake's internal module for determining `-gencode` parameters

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#109]
Apparently, CMake _can_ determine the compute capability relevant to your platform and generate the NVCC flags for you. But - it requires a package and another command. So let's drop our own custom code, ensure we include the package and issue the comand, etc.

**Comment by eyalroz** [comment]
@zingdle: Can you verify the push I've just made to fix this bug hasn't busted your docker / Windows builds?

**Comment by zingdle** [comment]
@eyalroz Sorry for my late response. I could help with my docker but I have no access to an equipped Windows machine. Maybe we could use CI to facilitate this. But AFAIK  we can only test whether the code can be built if we don't have additional GPU machines. See also https://github.com/travis-ci/travis-ci/issues/5911

I'm a little bit lost about the commit you're referring to. I'll try the latest commit on development branch as soon as I'm free.

**Comment by zingdle** [comment]
@eyalroz I've tested on my Linux machine and it worked well. 

Also, I've added travis on the development branch here https://github.com/zingdle/cuda-api-wrappers/commit/d21da2a958cfe37fec1903956f89cde2e01832ff. Unfortunately since there's no real GPU device on travis, the auto-detecting architecture part is skipped. You may take a look.

**Comment by eyalroz** [comment]
@zingdle : I had though about adding Travis builds, but like you said - I can't run any examples. Still, I guess it doesn't hurt. Create a PR for it please.

**Comment by eyalroz** [comment]
This was fixed as some point...
