### ISSUE TITLE
Support for CUDA arrays and texture memory

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#115]
I think it would be useful to provide wrappers to use CUDA arrays and texture memory. I am going to implement an initial functionality in the next two weeks. Maybe you can give me feedback on the implementation, such that I can later create a pull request.
See here:

https://github.com/codecircuit/cuda-api-wrappers

Some ideas:

```cpp

// only support for these types is given by cudaChannelFormatDesc
auto arr0 = cuda::array::create<float, 3>({w, h, d});
// Is it inconvenient to give the number of dimensions as a template parameter?
// Maybe this can be deduced from `w, h, d`
auto arr1 = cuda::array::create<unsigned, 3>({w, h, d});
auto arr2= cuda::array::create<int, 3>({w, h, d});

// only support for 2 and 3 dimensional arrays
auto arr3 = cuda::array::create<float, 2>({w, h});
auto arr4 = cuda::array::create<unsigned, 2>({w, h});
auto arr5= cuda::array::create<int, 2>({w, h});

auto ptr = cuda::memory::device::make_unique<float[]>(device, w * h * d);

// copy data into array
cuda::memory::copy(arr0, ptr.get());
// copy data into buffer
cuda::memory::copy(ptr.get(), arr1);

// Create a texture with reasonable defaults:
//	texDesc.addressMode[0]   = cudaAddressModeBorder;
//	texDesc.addressMode[1]   = cudaAddressModeBorder;
//	texDesc.addressMode[2]   = cudaAddressModeBorder;
//	texDesc.filterMode       = cudaFilterModePoint;
//	texDesc.readMode         = cudaReadModeElementType;
//	texDesc.normalizedCoords = 0;
//
// Create texture from an array
auto texture1 = cuda::texture::create(arr0);
// is this misleading, because texture1 is not owning memory?

// use in the kernel
cudaTextureObject_t raw = texture1.get(); // expose C-Object
cuda::launch(kernel, {1,1}, texture1.get(), ...);
```

**Comment by eyalroz** [comment]
> I think it would be useful to provide wrappers to use CUDA arrays and texture memory.

Sure, that's a good idea.

> Maybe you can give me feedback on the implementation, such that I can later create a pull request.

I will, but I'll need to give that part of the API another read.

A few comments for now:

1. What is the rationale for a stand-alone `create()` functions for arrays and textures, rather than using constructors directly?  (I have a potential answer, I want to know what's yours)
2. How come the `copy()` calls don't have numbers of bytes? (Actually, it's ugly that they even need numbers of bytes, but if you pass in pointers then they obviously do.)
3. You may want to allow specifying the number of dimensions implicitly, using 2 vs 3 arguments to the `create()` function.
4. Why aren't you specifying the device when creating the arrays?
6. I'm a bit worried about a potential confusion between the `cuda::array` namespace and between a potential `cuda::array` data structure, similar to `std::array`. Not sure how much this is a problem, but it needs a bit of thought.

**Comment by codecircuit** [comment]
> 1. What is the rationale for a stand-alone `create()` functions for arrays and textures, rather than using constructors directly?  (I have a potential answer, I want to know what's yours)

I tried to use already existing concepts of the `cuda-api-wrappers` library. E.g. there is currently a
`cuda::event::create` function, which creates a CUDA event and internally calls
`cudaEventCreate` and `cudaEventDestroy`. I thought this is somehow similar to
`cudaMalloc3DArray` and `cudaFreeArray`. But the library does not contain any
wrappers for objects which need to be allocated and freed yet. In that sense it might be more reasonable to have a similar interface like an `std::vector`. But without class template argument deduction we must write the dimensions of the array explicitly again. Thus it would be sth like:

```
cuda::array::array_t<float, 3> arr(device, w, h, d); 
```

> 2. How come the `copy()` calls don't have numbers of bytes? (Actually, it's ugly that they even need numbers of bytes, but if you pass in pointers then they obviously do.)

Thes size of the array can be save in the `cuda::array::array_t` class.

> 3. You may want to allow specifying the number of dimensions implicitly, using 2 vs 3 arguments to the `create()` function.

Yes, that makes sense.

> 4. Why aren't you specifying the device when creating the arrays?

I was missing that one. That also makes sense.

> 5. I'm a bit worried about a potential confusion between the `cuda::array` namespace and between a potential `cuda::array` data structure, similar to `std::array`. Not sure how much this is a problem, but it needs a bit of thought.

I agree. I think it would be ok if the user does not see the template parameter at all. E.g.

```cpp
auto arr = cuda::array::create<float>(device, w, h);
cuda::copy(arr, ptr);
```

**Comment by eyalroz** [comment]
> I tried to use already existing concepts of the `cuda-api-wrappers` library. E.g. there is currently a `cuda::event::create` function, which creates a CUDA event and internally calls `cudaEventCreate` and `cudaEventDestroy`. 

There's a reason I have a `create()` function - rather than what we should typically do with C++, which is just construct the object. And that is the fact that the `stream_t` object is templated over whether its assuming its device is the current one or not. I am not particularly happy with that part of my design, but I haven't figured out something better. If you need this templating in your class, then go ahead and have a `create()` function; otherwise I'm not sure I'd be for it (don't have a strong opinion right now).

> The size of the array can be save in the `cuda::array::array_t` class.

It can, and maybe it should - but what about the smart pointer? I don't think we should make it possible for `copy(arr, ptr)` to work but `copy(ptr, arr)` to fail. Or are you suggesting we have `copy()` accept a length on just one side? Anyway, you seem to be proposing new variants of `copy()`. That's a legitimate proposal, but I would separate it from this issue.

> ```c++
> auto arr = cuda::array::create<float>(device, w, h);
> ```

This is better than before, but you should also allow the other form, taking `dimensions_t` and with an explicit template parameter. By the way - would you want to have a `dim2` struct? Which the 2d array initializer could take, e.g. `create<float>(device, {w, h});?

**Comment by codecircuit** [comment]
> There's a reason I have a `create()` function - rather than what we should typically do with C++, which is just construct the object. And that is the fact that the `stream_t` object is templated over whether its assuming its device is the current one or not. I am not particularly happy with that part of my design, but I haven't figured out something better. If you need this templating in your class, then go ahead and have a `create()` function; otherwise I'm not sure I'd be for it (don't have a strong opinion right now).

Currently I see only this difference:

```cpp
// With create function
auto array = cuda::array::create<float>(device, {w, h})
// Without create function
cuda::array::array_t<float, 2> array(device, {w, h});
```
Thus for the version without a `create` function we save writing the number of dimensions explicitly. Is this worth to have a `create` function?

> It can, and maybe it should - but what about the smart pointer? I don't think we should make it possible for `copy(arr, ptr)` to work but `copy(ptr, arr)` to fail. Or are you suggesting we have `copy()` accept a length on just one side? Anyway, you seem to be proposing new variants of `copy()`. That's a legitimate proposal, but I would separate it from this issue.

Initially I thought of this:
```cpp
cuda::array::array_t<float, 2> arr(device, {w, h});
auto ptr = cuda::memory::device::make_unique<floa[]>(device, w * h);
cuda::memory::copy(ptr.get(), arr);
cuda::memory::copy(arr, ptr.get()); // both ways should be possible
```
My previous post was misleading. I did not think about support for smart pointers in the `copy` function. I think it is important to have wrappers for getting data in and out of an `cuda::array::array_t`, because writing this in the CUDA C API is annoying. I think wrapping this into the already existing `cuda::memory::copy` function, is intuitive. Do you think it is more reasonable to have another function for that? 

> This is better than before, but you should also allow the other form, taking `dimensions_t` and with an explicit template parameter. By the way - would you want to have a `dim2` struct? Which the 2d array initializer could take, e.g. `create(device, {w, h});?

Or we simply use `std::array<size_t, 2>` and  `std::array<size_t, 3>` for that?

**Comment by eyalroz** [comment]
> Currently I see only this difference

Remember that, sometimes, you want to avoid explicitly setting the current device if you know your array is on the current device.

> Do you think it is more reasonable to have another function for that?

Mmm... (looks at the API), no, it's probably better to unify copying. Especially since we have the synchronous and asynchronous variants of copying.



By the way - remember you want to support mipmapped arrays as well. I think.

> Or we simply use std::array<size_t, 2> and std::array<size_t, 3> for that?

I'm wondering whether we want to offer the flexibility. Also, remember you need a method returning the dimensions. It could always be a `dim3`, but I'm not certain that's the right thing to return for the 2D case.

**Comment by eyalroz** [comment]
Also note you're probably going to need to think about cudaPos, cudaExtent, and reconciling dimensions_t with whatever cudaExtent is made into, since they're kind of conflicting. You will either want to separate them, by qualifying their name with their intended use, or by namespace, or even unify them and change the API of some of the existing functions.

**Comment by codecircuit** [comment]
>  Remember that, sometimes, you want to avoid explicitly setting the current device if you know your array is on the current device. That may require an extra template parameter.

This is not the case for `cuda::event::create()` I think. So you must always give a device object to create an event. Do you think it would still be convenient to use the default device for the creation of `cuda::array::array_t` objects?

> By the way - remember you want to support mipmapped arrays as well. I think.

This exceeds my current time limit on this issue. Unless we don't see an urgent demand for this, we can implement it later.


Right now I have support for 3D and 2D CUDA arrays, copying To and From CUDA arrays to pointers synchronously and asynchronously, and texture memory. If you want to merge these features into the wrappers, you might want to have a look at my fork. Subsequently I can fix minor stuff, merge the commits reasonably and create a pull request.

**Comment by eyalroz** [comment]
> This is not the case for cuda::event::create() I think. So you must always give a device object to create an event. 

But if you create an event using the current device, you don't do it that way.

Have a look at  the [implementation of `device_t<AssumedCurrent>::create_event()`](https://github.com/eyalroz/cuda-api-wrappers/blob/master/src/cuda/api/multi_wrapper_impls.hpp#L84).

**Comment by eyalroz** [comment]
> This exceeds my current time limit on this issue. Unless we don't see an urgent demand for this, we can implement it later.

OK, but try not to make it so that we'd need a lot of breakage later to implement it.

> Right now I have support for 3D and 2D CUDA arrays, copying To and From CUDA arrays to pointers synchronously and asynchronously, and texture memory. If you want to merge these features into the wrappers, you might want to have a look at my fork. 

I'll do that today or tomorrow. I will, however, use my "library originator's prerogative", which I've just made up, to require that you write an example program which covers all of the new API functions/methods you're adding, or alternatively, a pseudo-unit-test for each of them. By "pseudo" I mean that I haven't integrated a proper unit testing mechanism into the repository right now, but that you write a program that just runs a bunch of functions which are essentially unit tests. The second option might be more code but it's probably simpler in that you don't have to make up some fancy overall narrative.

**Comment by eyalroz** [comment]
Oh wait... this is not good :-(  ... `event::create()`  is still using device ID's, while [it shouldn't](https://github.com/eyalroz/cuda-api-wrappers/issues/31). Maybe that's what threw you off.

**Comment by codecircuit** [comment]
Ah okay.... I was using `cuda::event::create` all the time :D. So you mean you there should be a a member function of `device_t` which creates an array?

**Comment by codecircuit** [comment]
> Oh wait... this is not good :-( ... the version of event::create() which uses device ID's is still outside the detail namespace, while it shouldn't. Maybe that's what threw you off.

and what about `cuda::memory::device::make_unique<float[]>(device.id(), N)`? This takes also the device id.

**Comment by codecircuit** [comment]
> Oh wait... this is not good :-( ... the version of event::create() which uses device ID's is still outside the detail namespace, while it shouldn't. Maybe that's what threw you off.

And what about `cuda::memory::device::make_unique`? It can also take the device id

**Comment by eyalroz** [comment]
So, I have the open bug I linked to, about making the APIs use the wrapper classes rather than IDs. It should be the case that a user doesn't need to know about "device IDs", "event IDs" and "stream IDs" - s/he can just know about devices, events and streams.

**Comment by codecircuit** [comment]
Do you agree with the current CUDA array and CUDA texture usage?

https://github.com/codecircuit/cuda-api-wrappers/blob/development/examples/by_runtime_api_module/array_management.cu

**Comment by eyalroz** [comment]
@codecircuit : I think it's good enough for a PR and a merge. Further nitpicks can come later.

**Comment by opto-guy** [comment]
I think `texture_view` should deactivate it's copy constructor/operator, since `texture_object` is basically an owning pointer. A move constructor/operator should be possible and helpful.

**Comment by eyalroz** [comment]
@opto-guy : Can you open a separate issue with your comment? I want to separate the previous discussions from this issue.
