### ISSUE TITLE
CMakeLists.txt cleanup

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#122]
Our `CMakeLists.txt` is long, a bit verbose in the comments and has some unnecessary code. Also, theres issue #121  . Let's refactor it.

**Comment by codecircuit** [comment]
Due to

https://github.com/eyalroz/cuda-api-wrappers/blob/development/examples/CMakeLists.txt#L33

If the examples are build the binaries are located in `cuda-api-wrappers/examples/bin`. Personally I consider this as an unclean build, because not all files, which are generated during the build are located in the build directory. For a clean build I would expect this behaviour:

```bash
# in the project directory
mkdir build
cd build
cmake ..
make -j
rm -rf * # removes all files, which are generated by the build
```

What is your opinion on that?

**Comment by eyalroz** [comment]
I should change it. But then, the script for running the examples should be copied and/or adapted to be aware of the build directory.

**Comment by codecircuit** [comment]
The script is basically a one-liner if you are in the directory of the binaries: `$ for f in *; do ./$f; done`. I would delete the script.

**Comment by eyalroz** [comment]
Done.

**Comment by eyalroz** [comment]
@codecircuit : So, anything else before I land this branch on the master branch again?

The span business will wait for later.

**Comment by codecircuit** [comment]
The comment here is not up to date any more
https://github.com/eyalroz/cuda-api-wrappers/blob/development/CMakeLists.txt#L49

Everything else seems to be fine now :).
