### ISSUE TITLE
Prevent incomplete initialization of launch_configuration_t

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#139]
Writing:

```
cuda::launch(kernel, {grid_dim, block_dim}, ...);
```

exhibits undefined behaviour, because it creates an object of type `launch_configuration_t` but without initializing member variable `dynamic_shared_memory_size`. It is very tempting just to write it in that way and if it compiles one can think that everything is fine; but in fact it is not. Also at least one sample `simpleIPC.cu` contains this pitfall. So how to deal with that? Maybe force the use of `make_launch_config`?

**Comment by eyalroz** [comment]
(grunt) Aww, man. And here I was believing I could just keep the launch config as a plain old struct.

... actually, it turns out that there is a simple solution... in C++14. It would be:
```
typedef struct {
	grid::dimensions_t       grid_dimensions; 
	grid::block_dimensions_t block_dimensions; 
	memory::shared::size_t    dynamic_shared_memory_size { 0u };
} launch_configuration_t;
```
but alas, we have to make do with C++11 facilities, where this is not possible :-(

We'll just need to spell out ctors and dtors I guess.
