### ISSUE TITLE
Should we drop the templatization of device_t and stream_t for simplicity of use? What about current device support?

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#142]
My initial choice for the stream and device wrapper class was a strong separation - via templates - between the cases of the current device (and streams on the current device), on one hand, and an arbitrary device on the other hand. The rationale is avoiding:

* obtaining the device ID before taking various actions.
* having to set the current device - and then set it back to whatever it was before after whatever action we've taken.

but maybe that's the wrong trade-off of benefits. After all, using the Runtime API is already "expensive" in the sense of necessitating opaque function calls, so what's another one here and there? Or another variable in a wrapper class?  - as opposed to the significant annoyance of users having to write `device_t<>` and `stream_t<>`. Who wants to do that? Blwech. Instead, of we could use a boolean field in the same class, and apply a condition in the implementation (or seal it away in some helper class like the scoped override).

Another dilemma is whether we even want to properly support the concept of a current device. We could just ignore it completely - decide that it doesn't matter and have no API which assumes there's a current device (on the outside), and rather - set it before any action, without reverting it afterwards. Setting the current device to the same value should cost just a function call and do nothing,, so - not very expensive. And it would make the implementation shorter and simpler. The drawback is that we could no longer have code which simply ignores the potential for multiple devices to exist (if we even have that right now, which is not too clear - since events take devices).

What do you - users of the library - think about these dilemmas?

(Contributors, and foremost @codecircuit   - your opinion is particularly interesting.)

**Comment by codecircuit** [comment]
I totally agree with the point that the templatization of classes `device_t` and `stream_t` make their usage more complicated. Especially If you build CUDA interfaces with the `cuda-api-wrappers`, it usually results in a template propagation of the parameter `AssumedCurrent`, which makes your interfaces more complicated.

I like the idea of dropping the concept of a current device. In practice this results in better readability and better portability to actual multi device code, for the cost of a little bit extra work (for most `cuda-api-wrappers` functions the `device` object is already needed anyway).

The overhead would be to call `cudaSetDevice` in basically every function, which calls a CUDA host API function, right? An alternative would be to save the current device internally and only call `cudaSetDevice` if the device, which is given to the function, is different. The drawback of the latter approach would be that the `cuda-api-wrappers` library does not know if the default device was changed outside the library; it is also more difficult to make this approach CPU thread safe.
We must ensure that there is no performance overhead when `cudaSetDevice` is called very often. We should do some benchmarks on that.

Before going for this implementation I would implement some kind of consistent versioning with CMake here. Such that users can write `find_package(cuda-api-wrappers 1.0.0)` and make a well rounded wrap up of the current implementation. Because dropping the templates from these classes is a huge change.

**Comment by eyalroz** [comment]
>  I would implement some kind of consistent versioning with CMake here.

I actually already have a first "released" version - right before merging your array support PR. [here](https://github.com/eyalroz/cuda-api-wrappers/releases).

> The overhead would be to call cudaSetDevice in basically every function, right? 

Yes. I'm 60% sure that, on the inside of it, they just set an integer and don't do anything else - but unfortunately they didn't make that an inline function. So, it costs at least one function call.

> I like the idea of dropping the concept of a current device. 

The counter-argument is that, well, the CUDA Runtime API  _has_ a current device. So I'd be telling people to ignore that. I wonder if that's justified. Also note that I can drop the templatization without dropping support for a "current device", it'll just require a few more calls to `cudaGetDevice()`.

**Comment by codecircuit** [comment]
> I actually already have a first "released" version - right before merging your array support PR. here.
Yes, but it would be consistent to implement that versioning into the CMake configuration.

> Yes. I'm 60% sure that, on the inside of it, they just set an integer and don't do anything else - but unfortunately they didn't make that an inline function. So, it costs at least one function call.

If it is just like that, there should be no doubt about dropping the templates.

> The counter-argument is that, well, the CUDA Runtime API has a current device
I do not have an example in mind, which shows that you can exploit the fact that there is a current device when using the `cuda-api-wrappers` right now. The real implicit model of the current device of the raw CUDA host API is already dropped when using the `cuda-api-wrappers`. E.g. what is the canonical way of creating events right now:

```
auto device = cuda::device::???::get()
auto event = device.event_create();
```

Or creating streams

```
auto stream = device.create_stream();
```

you always create the `device` object anyway.

>  it'll just require a few more calls to cudaGetDevice().

I do understand this point completely. Can you give an example on that?

**Comment by eyalroz** [comment]
> I do not have an example in mind, which shows that you can exploit the fact that there is a current device when using the cuda-api-wrappers right now

1. You can launch a kernel without mentioning a device.
2. When you get the current device, you don't actually make any CUDA API calls. But it's true that I've designed the stream and event class to have a device ID, so I didn't go all the way in exploiting the existence of a current device.

>  do understand this point completely. Can you give an example on that?

The device_t<true> class doesn't set the current device, nor does it know its ID. The scoped_device_setter<true> class doesn't do _anything_ at all.

**Comment by codecircuit** [comment]
So from the interface perspective the only thing which would change notably, if we drop the concept of a current device, is that you must give a `device` object to a `cuda::launch` call, right?

**Comment by eyalroz** [comment]
On that level - not really, there are a bunch of functions with variants for working on the current device, and a few of them here-and-there have variants for the current device. IIANM.

But the more significant point is an _intentional_ choice to make an aspwect of the CUDA API unavailable. I'm a bit worried about taking that step. One could make the argument that, instead, I should allow creating events and streams without specifying any device.

**Comment by codecircuit** [comment]
So on the one hand we have the arguments of readability and functional oriented concepts against the fact that there is an implicit current device in the CUDA programming model. 

Personally I use the wrappers because they increase readability and make CUDA programming in general less error prone. Going beyond the actual CUDA API is a strong point of the wrappers right now. Because otherwise you can just use an error-checking macro and the plain CUDA API.
