### ISSUE TITLE
imbue texture_view with the stream_t ownership model 

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#171]
As @opto-guy [notes](https://github.com/eyalroz/cuda-api-wrappers/issues/115#issuecomment-610972261), we are currently carelessly allowing for copying `texture_view`, despite it being a resource-owning class. This should be fixed. But - there's no reason not to allow non-owning copies. In fact, the ownership model of `stream_t` can be used for `texture_view`'s as well:

* A boolean `owning` field.
* Do nothing on destruction of non-owning texture views
* **edit:** deleted copy ctor.
* Move c'tor makes the moved-from texture view non-owning

@codecircuit : How does this sound to you?

**Comment by codecircuit** [comment]
I am not so sure about the non-owning copy c'tor. What would be the benefit of it? Maybe it just confuses the user of the class more, because he must know that the copy c'tor creates a non-owning object. If the copy c'tor is deleted the behaviour of the class is more obvious I would say. For the `stream_t` class the copy c'tor is also deleted.

**Comment by eyalroz** [comment]
@codecircuit Oh, right, I forgot about that. Ok, no copy ctor then.
