### ISSUE TITLE
Support for GPU Virtual Memory Management

### ISSUE THREAD

**Issue by neoblizz** [eyalroz/cuda-api-wrappers#174]
NVIDIA just announced low-level support for GPU virtual memory using a new set of memory APIs: https://devblogs.nvidia.com/introducing-low-level-gpu-virtual-memory-management/ with CUDA 10.2.

**Comment by eyalroz** [comment]
Hello @neoblizz ,

That API is, it seems, at the driver level rather than the Runtime level. And - the wrappers don't wrap the driver-level functionality. The entities and concepts the driver exposes are different - more basic - than what the runtime API exposes, so this would be a rather fundamental change.

**Comment by neoblizz** [comment]
Hey @eyalroz,

You are correct, but I presume that these driver level APIs will eventually be in the Runtime. As some of them are super useful. Please close this issue if you think this should be reopened when they actually are released in the cuda runtime.

On a similar memory management note, I have started actively using **cuda-api-wrappers** in my code  for some simple memory management stuff, going off of a conversation we had in emails a while ago. Expect me to actively contribute with pull requests as well.

**Comment by eyalroz** [comment]
@neoblizz : Well, if it enters the Runtime API I'll definitely add it. As for wrapping the driver level API - that might happen at some point, but... probably if enough people (more than one...) ask for it. Also, it might end up being a better idea having a separate library - or a separate subfolder within this library - for the runtime API and the driver API. I'm not sure about that though, it's just a though.

I am very open to pull requests, in general - for example, @codecircuit added support for CUDA arrays which I had not found the time to introduce (and was not experienced with). However, in order to make this more effective - I suggest we do some coordination before you're fully done with a PR. Specifically, I suggest you open issues about additions or modifications you're planning (and of course bugs if you find any); then I could comment on your intended design of the code and how it fits with the rest of the library.

Finally, if you happen to write something using **cuda-api-wrappers** that is relatively short (say < 1,000 lines of code or so) and can be made self-contained, I might be able to adapt it into a program for the `examples/` folder.

Thanks!

**Comment by eyalroz** [comment]
Closing for now - we'll see where this goes with CUDA 11.

**Comment by neoblizz** [comment]
Driver API would be really neat to have. An example of where that can get really powerful is when you can do lower level callbacks and modify how you would actually want the kernels to be launched. I implemented GPU virtualization using driver api awhile ago.

Feature I am interested in working on is cuda graphs (task graphs), right now that is bunched up with the "new features" issue (https://github.com/eyalroz/cuda-api-wrappers/issues/77). Do you recommend I make a separate issue for that and populate it or just work within issue #77?

> Finally, if you happen to write something using cuda-api-wrappers that is relatively short (say < 1,000 lines of code or so) and can be made self-contained, I might be able to adapt it into a program for the examples/ folder.

I intend to write modular code, so the work I am doing may not be a super simple example, but more of a simple `#include` library that one can use. But in my specific case, it is part of the larger project (gunrock/gunrock).

**Comment by eyalroz** [comment]
@neoblizz : Please open a separate issue for task graphs. When you do, I'll link to it from  #77 and add it to the CUDA 10 feature completion milestone. Let's keep things nice and tidy...

> it is part of the larger project (gunrock/gunrock).

Oh, I remember now that I wrote you a few months ago about the overlap with some of gunrock's infrastructure/utility code. In that case - if you've converted some of that to using cuda-api-wrappers or cuda-kat, "ping" me (perhaps by email) and I'll have a look for the ego boost of a good use of my code...

**Comment by neoblizz** [comment]
Haha, I'll be sure to do that, and maybe you could tell me how badly I have messed up and teach me how I could potentially use the wrappers better. 😅 

Thanks!
