### ISSUE TITLE
Allow for obtaining architecture and compute capability information at compile-time

### ISSUE THREAD

**Issue by neoblizz** [eyalroz/cuda-api-wrappers#182]
https://github.com/eyalroz/cuda-api-wrappers/blob/b33726d4cd72760fbd9d06c370e5fd5ee59c7d31/src/cuda/api/device_properties.cpp#L24-L37

For several things, we need these values known at compile time. I am not familiar with `find_if`, will it be able to find the value for the corresponding arch at compile time?

This is necessary for simple and performance critical tasks, stuff like kernel launch/bound configs, static shared memory, etc.

**Comment by eyalroz** [comment]
The main problem here is that in C++11, most of the standard library - including `std::array` and `<algorithm>` functions - are non-constexpr. So we would need to either write a bunch of infrastructure code for C++11-constexpr work, or find/choose a C++11 library which provides this functionality.

That would also encourage making more of the library header-only.

**Comment by neoblizz** [comment]
I guess we are looking for something like https://github.com/serge-sans-paille/frozen? Problem is further added dependencies.

**Comment by neoblizz** [comment]
I am using C++14, and I see improved support for `constexpr` for that. But I am assuming the current implementation of device_properties.cpp will still not provide results at compile time with C++14?

**Comment by eyalroz** [comment]
@neoblizz : 

1. Adding a dependency on something like `frozen` is way too much.
2. At some point it would be reasonable to increase the minimum expected C++ version from C++11 to C++14. I'm not sure we are at that point yet. (You can try to convince me I suppose.)
3. Instead of something smarter, we could try something dumber and less generic; but which would make it easier on us to be constexpr.

**Comment by neoblizz** [comment]
My issue with device_properties specifically is the following:

I have applications that are very performance sensitive, graph algorithms that finish within milliseconds. Any time spent not doing that graph thing is performance regression for me. So, we take all the kernel configurations and anything to do with setting things up to compile time, so what you really measure is simply the algorithm you write and would want to run on really large graphs.

The other case is that there are things that simply require compile time knowledge. Use of static shared memory for example, or setting up launch bounds is another example. And a bunch of things can be dependent on it at a programmer level.

I know even if we move to C++14, find_if is not constexpr, so this will require another look. I think C++20 supports find_if constexpr, but CUDA is not there yet.

**Comment by eyalroz** [comment]
> A good question to ask here is who is using CUDA 8? And I don't quite know the answer to that. Because the support for C++14 was added in CUDA 9 I believe, which allowed for really clean lambda operators, use of auto, further constexpr support, etc. all in device code.

Lots of distributions from a few years ago use CUDA 8. And - production environments of lots of companies utilizing GPUs. Upgrading to a new CUDA version is a big deal for a large company with a running product and clients which depend on it.

But - that actually doesn't matter much in itself, because the C++14 support in CUDA 9 is for device-side code. You could very well compile your host-side code with a C++14-capable compiler and only use nvcc for whatever really needs to be close to the device.

Anyway, I think I'll make the upcoming release of cuda-api-wrappers compatible with C++11, then perhaps switch to requiring C++14 for the next one.

**Comment by eyalroz** [comment]
> I have applications that are very performance sensitive, graph algorithms that finish within milliseconds. Any time spent not doing that graph thing is performance regression for me. 

My paradigm is that the overhead on these API wrappers is relatively cheap compared to device-side work. But I see what you mean.

> So, we take all the kernel configurations and anything to do with setting things up to compile time, so what you really measure is simply the algorithm you write and would want to run on really large graphs.

But can't you just do the kernel configuration at run-time, on startup, before taking any queries/graphs?

**Comment by neoblizz** [comment]
> But can't you just do the kernel configuration at run-time, on startup, before taking any queries/graphs?

That's what I am doing right now, but some dependencies that I rely on require launch boxes to be configured at compile time or use a default that is worse. Again, these properties are known at compile time and we can expect compiler level optimizations to also benefit from them. Now, whether nvcc actually does a good job that I am not sure of.

Things that we know nvcc optimizes for;
- register usage
- loop unrolling
- data packing
- ilp

**Comment by eyalroz** [comment]
@neoblizz : See if what I've done satisfies your requirements. You'll need to use the standalone `constexpr` functions in `cuda::device::detail` rather than the methods, which are throwing and guarantee no error.

**Comment by neoblizz** [comment]
These changes are perfect for me, switching to using this. Thank you!

**Comment by eyalroz** [comment]
@neoblizz : They're not actually perfect. You see, you'll be depending on internals of the library rather than on its proper interface. To make all of this stuff properly constexpr, I would have had to constrain `compute_architecture_t` and `compute_capability_t` to only be able to have one of the recognized values. This is possible, but it would mean the API wrappers can't really be forward-compatible with future CUDA versions. Or, not without playing with the build-time defines.

**Comment by neoblizz** [comment]
Can you clarify on why it wouldn't be forward-compatible? I am trying to understand from a user's perspective on how I can avoid using the internals. Because I presume they can/will be changed in the future and I wouldn't want my code to break because I wasn't using the actual intended api.

Also, a minor fix is needed: https://github.com/eyalroz/cuda-api-wrappers/commit/4dd982a8d6ec9c65430fc5675f54b395dd5a412d#diff-bbf5cead5d556f13f2a0c58a3eb26d10R227-R263 all fallback to `max_in_flight_threads_per_processor(cc.architecture)`, when it should fallback to the corresponding property.

**Comment by eyalroz** [comment]
I mean, that if I say "architectures above 7 are invalid", then when Ampere comes out, you would not be able to use `compute_architecture_t` with it.
