### ISSUE TITLE
Increase safety of using CUDA events

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#226]
To my mind there exsts one problem with CUDA events. If they are not recorded and `cudaEventQuery` is used to determine if the event has occurred, it returns actually that the event occurred although it was never recorded. Maybe it is possible that the Wrappers actually return `false` if `has_occurred()` is called on a not recorded event? What you you think?
Or we add another function `recorded_and_has_occurred()`?

**Comment by eyalroz** [comment]
I agree that `cudaEventQuery()` shouldn't say a never-registered event has occurred. The question is whether it's reasonable for us to protect against that. I don't think we can do so reliably, because we can't really track registration of this event elsewhere. And trying to do this would exceed the scope of the wrappers, which try to be a minimal abstraction over the Runtime API (and soon the driver API) functionality, as it exists.

What I do think you (or me) could do is file a bug report about this with NVIDIA.

**Comment by codecircuit** [comment]
I think they consider it as a feature and not as a bug. From the documentation of `cudaEventRecord`:

> cudaEventRecord() can be called multiple times on the same event and will overwrite the previously captured state. Other APIs such as cudaStreamWaitEvent() use the most recently captured state at the time of the API call, and are not affected by later calls to cudaEventRecord(). Before the first call to cudaEventRecord(), an event represents an empty set of work, so for example cudaEventQuery() would return cudaSuccess.

**Comment by eyalroz** [comment]
@codecircuit : Well, not all of NVIDIA is a single person; and the person writing the documentation wanted to make it sound reasonable...
