### ISSUE TITLE
Make "cooperativity" be part of the launch configuration

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#258]
At the moment, the user must specify, when launching a kernel, whether thread blocks should be allowed to cooperate or not. This is a bit cumbersome, and also increases the number of kernel launch functions and methods, which is already not so small.

On the other hand, our wrapped kernel class does indicate whether thread blocks should be allowed to cooperate, and putting that flag into a launch config may remove the ability to hard-code that requirement.

Yet again on the first hand - why should we not have the ability to hard-code requirements for other aspects of the launch, into a `kernel_t`? Dynamic shared memory size requirements, and even block and grid size requirements? A kernel can certainly have those.

I would lean in favor of having less functionality in `kernel_t` and making the move, since this library is just for wrapping, not for beefier abstractions.

Why do you think @codecircuit , @raplonu, @quxflux   et al. ?

**Comment by codecircuit** [comment]
With 'hard-code' you mean dynamic member variables of class `kernel_t`? So you suggest to move the kernel launch configuration (partially) into the `kernel_t` class?

**Comment by codecircuit** [comment]
Can you please further explain:

> On the other hand, our wrapped kernel class does indicate whether thread blocks should be allowed to cooperate, and putting that flag into a launch config may remove the ability to hard-code that requirement.

Do you mean to save the kernel launch configuration into objects of class `kernel_t` in favor of saving them in a separate kernel launch config object?

**Comment by codecircuit** [comment]
As far as I understand your point you want to discuss how much 'kernel launch configuration' should be saved in class `kernel_t`. Is that correct?

I agree with your point of having less functionality in class `kernel_t` and e.g. move the thread block cooperation flag into the kernel launch config, instead of having it as a member variable in `kernel_t`. Due to issue #236, I think it is not completely safe to use the `kernel_t` class when launching a CUDA kernel and I personally avoid that completely. Nevertheless, I think the `kernel_t` class is handy, to e.g. check kernel attributes and GPU occupancy. As far as I see it, the member variable `thread_block_cooperation` of class `kernel_t` is only used in the ctor and getter function. Thus, the member functions of class `kernel_t` should not be affected if this member variable is removed.

**Comment by eyalroz** [comment]
> As far as I understand your point you want to discuss how much 'kernel launch configuration' should be saved in class kernel_t. Is that correct?

Now... I'm wondering whether to add `bool block_cooperation` to `launch_configuration_t`, and removing it from `kernel_t`...

**Comment by eyalroz** [comment]
@codecircuit : Done.

**Comment by eyalroz** [comment]
@codecircuit : I've deleted 63 more lines than I've added, so it has to be good :-P

Reminding you to possibly have a look at the driver-wrappers branch.
