### ISSUE TITLE
unique_ptrs throws an instance of 'cuda::runtime_error' in version v0.5.1 

### ISSUE THREAD

**Issue by DiamonDinoia** [eyalroz/cuda-api-wrappers#336]
The following code:
```cuda
#include <cuda/api.hpp>
int main() {
    cuda::memory::device::unique_ptr<double[]> device_pointer(
        cuda::memory::device::make_unique<double[]>(cuda::device::current::get(), 16));
   return 0;
}
```
causes:
```
terminate called after throwing an instance of 'cuda::runtime_error'
  what():  Freeing device memory at 0x0x07faca2c00000: invalid argument

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
I think is a bug introduced in verson v0.5.1 as it works fine with version v0.5.0.

**Comment by eyalroz** [comment]
@DiamonDinoia Can you try this with the HEAD of the development branch? I think it's been fixed.

**Comment by eyalroz** [comment]
Yeah, I think this is a dupe of #327 and should be resolved now.

**Comment by DiamonDinoia** [comment]
Yes, it seems the same issue. It works with  the HEAD development branch.

**Comment by eyalroz** [comment]
@DiamonDinoia : Thank you for reporting this, though.

If you use the library in an interesting project, I'd love to hear about it... also if you have any suggestions / things you think are missing or existing-but-inconvenient.

Finally, the reason this went unnoticed is probably because people typically work with an explicit context proxy in a certain scope, in which case I do not need to jump through hoops to to manage global state (the device primary context) :-)
