### ISSUE TITLE
Provide instalation guide for installing with CMakeLists

### ISSUE THREAD

**Issue by EmmanuelMess** [eyalroz/cuda-api-wrappers#381]
Provide instalation guide for installing with CMakeLists.

**Comment by eyalroz** [comment]
Hmm. 
```
cd /path/to/cuda-api-wrappers/
ccmake -B build
cmake --install build
```
I guess it may not be obvious to people who don't have experience with CMake...

**Comment by EmmanuelMess** [comment]
But that installs on the current computer. I suppose install isn't the best word to have used in the issue.
I want the dependecy to be in the project as a submodule, or make it download automatically to a "project controlled" folder.

I have done this to achieve it on my current project:

```
cd project_folder
gh repo clone eyalroz/cuda-api-wrappers
```

And then add the dependency to CMakeLists.txt:

```
target_include_directories(ProjectName PRIVATE "cuda-api-wrappers/src")
```

**Comment by EmmanuelMess** [comment]
I am getting undefined reference errors though:
```
cuda-api-wrappers/src/cuda/api/error.hpp:220: referencia a `cuGetErrorString' sin definir
cuda-api-wrappers/src/cuda/api/error.hpp:397: referencia a `cuInit' sin definir
```

**Comment by eyalroz** [comment]
> I want the dependency to be in the project as a submodule

1. Install cuda-api-wrappers to `/some/where/cuda-api-wrappers`
2. Set `CMAKE_PREFIX_PATH` for your  build to include `/some/where/cuda-api-wrappers`
3. `find_package(CUDAToolkit)` and `find_package(cuda-api-wrappers)` in the repository depending on cuda-api-wrappers. 

Now you get CMake targets - `cuda-api-wrappers::runtime-and-driver`, `cuda-api-wrappers::nvrtc`, `cuda-api-wrappers::nvtx` - which also have their dependencies pulling in CUDA libraries proper. That will probably also resolve your undefined references - which are due to you not linking against the CUDA driver library (`CUDA::cuda_driver` in CMake).



, or make it download automatically to a "project controlled" folder.

**Comment by EmmanuelMess** [comment]
Adding `target_link_libraries(ProjectName cuda)` worked for fixing the missing refs problem, so my solution seems to work, do tell me if it is clearly wrong. 

Your solution requires an installation for the library to run, which seems like a step that could be skipped seeing that the project has a CMakeLists capable of building the library.

**Comment by eyalroz** [comment]
@EmmanuelMess : Yes, that could be skipped, if I adapted the CMakeLists.txt for such use. That should be a separate issue... would you like to open it?

**Comment by eyalroz** [comment]
Actually, I will add some guidance for using the library to the README.md, so this stays open for now. And I want to thank you for pointing this out, I've not dismissed the request.

**Comment by eyalroz** [comment]
@EmmanuelMess : Please have a look at the README on the development branch, and let me know if the new section about using the library with your project is satisfactory.

**Comment by EmmanuelMess** [comment]
Added a few comments to the other issue. Apart from that, I would not use a numbered list for the options, as it looks like steps, not exclusive options :)
