### ISSUE TITLE
region_pair has no type information

### ISSUE THREAD

**Issue by EmmanuelMess** [eyalroz/cuda-api-wrappers#383]
`region_pair` has no type information, maybe it should be templated:

```cuda
cuda::memory::mapped::region_pair time = cuda::memory::mapped::allocate(device, sizeof(Time));
```

To:
```cuda
cuda::memory::mapped::region_pair<Time> time = cuda::memory::mapped::allocate<Time>(device);
```

And not have to cast the pointer on use.

**Comment by eyalroz** [comment]
First note that mapped memory is mostly a legacy feature, and these days you would probably get more mileage out of managed memory (= mapped but with the same addresses for both the CPU and GPU regions).

--------------

Now, about the type information - this is actually intentional. The standard library's allocators are spectacularly mis-designed in their being templated on a data type, while, in fact, they absolutely don't need that information. See [Andrei Alexandrescu's CppCon lecture](https://www.youtube.com/watch?v=LIb3L4vKZ7U) on how allocators and regions should look like.

More to the point: The allocation does not depend on the type, only on its size (and alignment, which we currently ignore anyway). And remember you can use a `unique_ptr` with a type anyway:
```
auto my_ptr = cuda::memory::managed::make_unique<Time>(device);
```
I'm not too happy about even having this (I think we should only have smart regions, not smart pointers, considering Alexandrescu's arguments), but it's there and it works. I may also be adding make_unique_region sometime (and don't know if it'll be typed or not).

**Comment by EmmanuelMess** [comment]
I'll check managed memory, and make unique. Thanks!
