### ISSUE TITLE
Support colcon build

### ISSUE THREAD

**Issue by wep21** [eyalroz/cuda-api-wrappers#460]
@eyalroz Thank you for developing this awesome library. I would like to use this library in [ROS](https://docs.ros.org/en/humble/) project, so can I add package.xml to build this library with [colcon](https://colcon.readthedocs.io/en/released/) build system?

**Comment by eyalroz** [comment]
Well... maybe. On the one hand, naturally I want to encourage wider use of the library; but - is it common for C++ libraries to have such a file? I'll admit I've never head of the "Robot Operating System" or colcon before.

**Comment by eyalroz** [comment]
spdlog doesn't have one, cxxopts doesn't, MS GSL doesn't, Boost doesn't...

So, doesn't it make more sense to keep these package.xml files separately from the libraries you intend to use?

**Comment by wep21** [comment]
Okay, I will use `fetchcontent` as you describe in readme. Thank you for considering it.

**Comment by kenji-miyake** [comment]
@eyalroz Thank you for considering it.
Just FYI, I'll let you know several pieces of information.

As an example, there is a library https://github.com/Neargye/magic_enum that is widely used and has `package.xml`.
The PR to add `package.xml` is https://github.com/Neargye/magic_enum/pull/161.

Regarding `spdlog`, `Boost`, `fmt`, and etc., they don't have `package.xml` because they are released to `apt`. We install them via `apt`.
The list of libraries that can be installed via `apt` is here: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml

If it's difficult for the upstream package to add `package.xml`, there is an alternative way called vendor packages.
For example, https://github.com/tier4/osqp_vendor.
A vendor package fetches the upstream package and wraps it like this: https://github.com/tier4/osqp_vendor/blob/1ea3682dacc08bd05d301098b202e74bd6416251/CMakeLists.txt#L23-L24

Also, talking about the background, 
in https://github.com/autowarefoundation/autoware.universe/pull/2810, we were originally considering creating a vendor package.
https://github.com/autowarefoundation/autoware.universe/tree/8eefe2150cbe4e5a43af71590ab9b5842b62209c/common/cuda_api_wrappers
As we thought it might be efficient to manage the meta files in the upstream repository, we asked @wep21 to ask the upstream author (you) whether it's possible or not.

Seeing your comments, adding `package.xml` to this repository would be difficult for you, but it's okay for us.
We'll continue using a vendor package or consider another way.

Thank you.
