### ISSUE TITLE
kernel compilation option --gpu-architecture can cause NVRTC_ERROR_INVALID_OPTION

### ISSUE THREAD

**Issue by DanCher1403** [eyalroz/cuda-api-wrappers#509]
on NVIDIA L40 GPUs, when adding the following option:
`m_compOpts.add_target(m_device.compute_capability());`

it results with:
`--gpu-architecture=sm_89`
(complete list of options is:
`--device-as-default-execution-space --prec-sqrt=false --prec-div=false --std=c++17 --gpu-architecture=sm_89 -DCUDA ...`)

and causes `NVRTC_ERROR_INVALID_OPTION` kernel compilation error.

Also, the error message is not very informative and does not mention what is the invalid option and its value:
`Failed invoking compiler for CUDA C++ program at 0x07fae240a1c80: NVRTC_ERROR_INVALID_OPTION`

Seen on:
` NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0`

**Comment by eyalroz** [comment]
1. What version of CUDA are you using? If it's 12.0, try it also with 12.1 and let me know whether you get the same error.
2. Please render the full compilation options and copy them here, to help reproduce the issue.

**Comment by eyalroz** [comment]
After ironing out the situation with @DanCher1403 , it seems the cause of the error was the executable dynamically-loading NVRTC 11.2 instead of 12.0/12.1 And, indeed, NVRTC 11.2 does not support `--gpu-architecture=sm_89`. So, not a bug. It is too bad, however, that NVIDIA doesn't tell us _which_ option was invalid.

**Comment by eyalroz** [comment]
Also, see #510
