### ISSUE TITLE
cuda::event_t inconsistently/confusingly copyable

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-api-wrappers#99]
```cpp
#include <cuda/api_wrappers.hpp>

#include <vector>

struct Foo {
	cuda::event_t a = cuda::event::create(cuda::device::current::get());
	cuda::event_t b = cuda::event::create(cuda::device::current::get());
};

void f(std::vector<Foo>& v) {
	Foo f;
	f.a.record();
	v.push_back(f);
}

int main() {
	std::vector<Foo> v;
	f(v);
	v.back().b.record(); // error
}
```

Should copying and assignment be disabled for `cuda::event_t`? I think this would
enhance useability. I just stepped over the issue in the code snippet above.

See also https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#r1-manage-resources-automatically-using-resource-handles-and-raii-resource-acquisition-is-initialization

They suggest to disable copying and assignment for such types (`class Port` in the example)

**Comment by eyalroz** [comment]
Well, `event_t` does have copy constructors. But let me check this code.

**Comment by eyalroz** [comment]
I think it might actually be a violation of the "rule of five".

**Comment by eyalroz** [comment]
... but then, it's true that you can't just make _copies_ of unique_ptr's and have those copies implicitly marked marked non-owning. So maybe I should prevent copying after all?

**Comment by jvschroeder** [comment]
I don't really like a mixture of owning/non-owning without ref-counting (since then you might have a non-owning instance after the resource has been freed). I'd suggest to either implement the semantics of std::unique_ptr<> (i.e. not copy but only move constructible) or std::share_ptr<> (ref-counting, thus making sure that, as long as there is an instance the underlying resource hasn't been freed). Since you seem to believe that it is ok to have access to the same event in multiple places I'd vote for the latter unless there are potential thread-safety issues?

**Comment by eyalroz** [comment]
@jvschroeder There is only one object owning an event (that's not going to change). I've allowed a non-owning version because sometime the owner is not you, and you might get a raw CUDA event ID from someone else; same thing goes for streams (but not for devices). Also, a `shared_ptr`-like class requires quite a bit of overhead. So I'm leaning towards following `unique_ptr` more closely - which is what the patch does. It will make @codecircuit 's example fail to compile:
```
/usr/include/c++/6/ext/new_allocator.h:120:4: error: use of deleted function ‘Foo::Foo(const Foo&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.cpp:5:8: note: ‘Foo::Foo(const Foo&)’ is implicitly deleted because the default definition would be ill-formed:
 struct Foo {
        ^~~
a.cpp:5:8: error: use of deleted function ‘cuda::event_t::event_t(const cuda::event_t&)’
In file included from ./cuda/api_wrappers.hpp:29:0,
                 from a.cpp:1:
./cuda/api/event.hpp:199:2: note: declared here
  event_t(const event_t&) = delete;
  ^~~~~~~
a.cpp:5:8: error: use of deleted function ‘cuda::event_t::event_t(const cuda::event_t&)’
 struct Foo {
        ^~~
In file included from ./cuda/api_wrappers.hpp:29:0,
                 from a.cpp:1:
./cuda/api/event.hpp:199:2: note: declared here
  event_t(const event_t&) = delete;
```

**Comment by eyalroz** [comment]
Oh, wait - I'll need to do the same thing for streams.

**Comment by jvschroeder** [comment]
Thanks for the explanation! Considering this I think your approach of simply delete-ing the implicit copy constructor is appropriate. What I don't really see is why one needs the explicit constructor given that there already is cuda::event::wrap ?

**Comment by eyalroz** [comment]
@jvschroeder : Because `wrap()` is essentially just a fancy name for this kind of construction, so I'm not sure I have the "right" to take it away. I've marked it `explicit` though. The patch does the same thing basically for both events and streams. 

Interestingly, It doesn't break any of the example code.

**Comment by eyalroz** [comment]
@codecircuit : Another reason to give the development branch a spin...

**Comment by codecircuit** [comment]
Thanks for the detailed discussion. I think if my sample fails to compile it is fine.
